services:
  - type: web
    name: pbt-survey-bot
    env: python
    buildCommand: ""
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: GOOGLE_CREDS_JSON
        sync: false
      - key: SPREADSHEET_NAME
        sync: false
